### PR TITLE
Fix for issue #3

### PR DESCRIPTION
**Pull request by hhoeschle**
see description of issue here #3

### CODE REVIEW

**Comment by hhoeschle** [comment]
No problem, it was also a personal experiment in how to set up a fork, commit, and then start a pull request.

**Comment by ererkka** [comment]
As @manuelma said, we are not yet accepting pull requests here at GitHub. We can of course merge your branch manually at our private repository. Thanks for submitting!

**Comment by ererkka** [comment]
Sorry, we can of course keep this open for the manual merge.

**Comment by Tasqu** [comment]
I believe this pull request is no longer relevant due to updates to both SpineInterface and SpineDBAPI, so closing this.

**Pull request closed without merging**
