### PR TITLE
17 improve documentation

### LINKED ISSUE #17: Improve documentation
In GitLab by @manuelma on May 9, 2019, 18:48

Again, top priority. Maybe it's time to work on this now.

### PR DESCRIPTION
**Pull request by tarskul**
Overhaul of the documentation:
+ updated the readme
+ updated the intro of the documentation
+ upgraded the existing tutorial
+ added a new tutorial.
+ added a new test that will fail if the code of the tutorial files fail

Fixes #17

## Checklist before merging
- [x] Documentation is up-to-date
- [x] Release notes have been updated
- [x] Unit tests have been added/updated accordingly
- [x] Code has been formatted nicely
- [x] Unit tests pass

### CODE REVIEW

**Comment by tarskul** [comment]
As this is my first pull request for Spine Interface, I guess it is best to hold off from merging until one of the more experienced developers has come back from holidays. (Even though everything looks alright to me)

**Review by Tasqu — COMMENTED** [review]
Honestly, I'm not even sure how SpineInterface.jl `master` handles its documentation. When trying to build it locally, one has to manually add SpineInterface into the `docs` environment, as its not there for whatever reason. I'm guessing this is a bug, @manuelma ?

Regardless, the removal of the `examples/data/example.sqlite` seems to cause doctest failures. E.g. the docstring of the function for accessing an ObjectClass `src/api/core.jl` tries to refer to a database that no longer exists. I'm guessing we'll have to update the `jldoctest` blocks in the docstrings if we want to avoid those issues.

I can't really recommend merging as is, as I'm not sure if the CI workflow would pass. Fixing the doctests might be a bit of work, though.

**Comment by tarskul** [comment]
Strange, the checks seem to pass both locally and online for me... I removed the docstring tests in favour of testing the example files directly. I'll check again, maybe I missed a few.

**Review by Tasqu — APPROVED** [review]
Might be a Julia version thing on my end as well. I'm using Julia 1.9.2, and looking at the failing doctests, most of them seem to be type conflicts between resulting `Vector` and expected `Array{T,1}` outputs. Still, this branch now has less doctest failures than `master` on my machine, so that's an improvement. Good to go as far as I'm concerned.

**Pull request merged**
